version: '3.8'
services:
  database:
    container_name: mysql-tech-challenge-client-registration
    image: mysql:8.0.30
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3341:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: techchallengeclient


